"""Hall Allocation Fix

Revision ID: 04f4d07f5d98
Revises: 5c279eb02949
Create Date: 2025-08-16 14:01:41.007944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04f4d07f5d98'
down_revision: Union[str, None] = '5c279eb02949'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('halls', 'category_allocated',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('halls', 'category_allocated',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
