"""Fixes

Revision ID: 095cb3fd0f8d
Revises: 30859074fc8c
Create Date: 2025-12-07 22:16:41.268835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '095cb3fd0f8d'
down_revision: Union[str, None] = '30859074fc8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hall_floors',
    sa.Column('floor_id', sa.UUID(), nullable=False),
    sa.Column('hall_id', sa.Integer(), nullable=False),
    sa.Column('floor_no', sa.Integer(), nullable=False),
    sa.Column('age_range', sa.Enum('10-17', '18-25', '26-35', '36-45', '45-55', '56-65', '66-70', '71+', name='age_range_enum'), nullable=True),
    sa.Column('no_beds', sa.Integer(), nullable=True),
    sa.Column('last_assigned_bed', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('full', 'not-full', name='floor_status'), nullable=False),
    sa.ForeignKeyConstraint(['hall_id'], ['halls.id'], ),
    sa.PrimaryKeyConstraint('floor_id')
    )
    op.create_index(op.f('ix_hall_floors_floor_id'), 'hall_floors', ['floor_id'], unique=False)
    op.drop_constraint('categories_hall_name_fkey', 'categories', type_='foreignkey')
    op.drop_column('categories', 'no_beds')
    op.drop_column('categories', 'hall_name')
    op.drop_column('categories', 'floor_allocated')
    op.add_column('halls', sa.Column('gender', sa.Enum('male', 'female', name='gender_enum'), nullable=False))
    op.drop_column('halls', 'no_allocated_beds')
    op.alter_column('users', 'floor',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.create_foreign_key(None, 'users', 'hall_floors', ['floor'], ['floor_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'floor',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.add_column('halls', sa.Column('no_allocated_beds', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('halls', 'gender')
    op.add_column('categories', sa.Column('floor_allocated', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('categories', sa.Column('hall_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('categories', sa.Column('no_beds', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('categories_hall_name_fkey', 'categories', 'halls', ['hall_name'], ['hall_name'])
    op.drop_index(op.f('ix_hall_floors_floor_id'), table_name='hall_floors')
    op.drop_table('hall_floors')
    # ### end Alembic commands ###
