"""ticketing table updatess

Revision ID: 0a6603ead8d7
Revises: 8349a8f89e5d
Create Date: 2026-03-02 09:11:11.827876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a6603ead8d7'
down_revision: Union[str, None] = '8349a8f89e5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_records', sa.Column('meal_type', sa.String(), nullable=False))
    op.drop_constraint('uq_minister_date', 'meal_records', type_='unique')
    op.create_index(op.f('ix_meal_records_meal_type'), 'meal_records', ['meal_type'], unique=False)
    op.create_unique_constraint('uq_minister_meal_session', 'meal_records', ['minister_id', 'date', 'meal_type'])
    op.add_column('ministers', sa.Column('identification_meal_number', sa.Integer(), nullable=False))
    op.add_column('ministers', sa.Column('medical_issues', sa.String(), nullable=True))
    op.add_column('ministers', sa.Column('local_assembly', sa.String(), nullable=True))
    op.add_column('ministers', sa.Column('local_assembly_address', sa.String(), nullable=True))
    op.add_column('ministers', sa.Column('profile_picture_url', sa.String(), nullable=True))
    op.add_column('ministers', sa.Column('object_key', sa.String(), nullable=False))
    op.add_column('ministers', sa.Column('date_presigned_url_generated', sa.Date(), nullable=False))
    op.alter_column('ministers', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'ministers', ['identification_meal_number'])
    op.create_unique_constraint(None, 'ministers', ['object_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ministers', type_='unique')
    op.drop_constraint(None, 'ministers', type_='unique')
    op.alter_column('ministers', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('ministers', 'date_presigned_url_generated')
    op.drop_column('ministers', 'object_key')
    op.drop_column('ministers', 'profile_picture_url')
    op.drop_column('ministers', 'local_assembly_address')
    op.drop_column('ministers', 'local_assembly')
    op.drop_column('ministers', 'medical_issues')
    op.drop_column('ministers', 'identification_meal_number')
    op.drop_constraint('uq_minister_meal_session', 'meal_records', type_='unique')
    op.drop_index(op.f('ix_meal_records_meal_type'), table_name='meal_records')
    op.create_unique_constraint('uq_minister_date', 'meal_records', ['minister_id', 'date'])
    op.drop_column('meal_records', 'meal_type')
    # ### end Alembic commands ###
