"""Age Range Fix

Revision ID: 0f986d513ec9
Revises: 52db91ed7035
Create Date: 2025-12-08 19:26:56.721009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f986d513ec9'
down_revision: Union[str, None] = '52db91ed7035'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hall_floors', sa.Column('age_ranges', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('hall_floors', 'age_range')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hall_floors', sa.Column('age_range', postgresql.ENUM('10-17', '18-25', '26-35', '36-45', '45-55', '56-65', '66-70', '71+', name='age_range_enum'), autoincrement=False, nullable=True))
    op.drop_column('hall_floors', 'age_ranges')
    # ### end Alembic commands ###
