"""ticketing table updatess ver 2

Revision ID: 10acccfd7ee6
Revises: 0a6603ead8d7
Create Date: 2026-03-02 09:43:39.561722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10acccfd7ee6'
down_revision: Union[str, None] = '0a6603ead8d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ministers', 'identification_meal_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ministers', 'identification_meal_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
