"""initial migration

Revision ID: 30859074fc8c
Revises: 
Create Date: 2025-12-05 14:26:21.151016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30859074fc8c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('halls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hall_name', sa.String(), nullable=False),
    sa.Column('no_beds', sa.Integer(), nullable=False),
    sa.Column('no_allocated_beds', sa.Integer(), nullable=False),
    sa.Column('no_floors', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hall_name')
    )
    op.create_index(op.f('ix_halls_id'), 'halls', ['id'], unique=False)
    op.create_table('image_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_index(op.f('ix_image_categories_id'), 'image_categories', ['id'], unique=False)
    op.create_table('phone_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('time_registered', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_phone_numbers_id'), 'phone_numbers', ['id'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.Column('hall_name', sa.String(), nullable=False),
    sa.Column('floor_allocated', sa.Integer(), nullable=False),
    sa.Column('no_beds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hall_name'], ['halls.hall_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_name', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('in-use', 'inactive', name='image_status_enum'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['image_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_name'),
    sa.UniqueConstraint('image_url')
    )
    op.create_index(op.f('ix_images_id'), 'images', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('age_range', sa.Enum('10-17', '18-25', '26-35', '36-45', '45-55', '56-65', '66-70', '71+', name='age_range_enum'), nullable=False),
    sa.Column('marital_status', sa.String(), nullable=False),
    sa.Column('no_children', sa.Integer(), nullable=True),
    sa.Column('names_children', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('arrival_date', sa.Date(), nullable=False),
    sa.Column('medical_issues', sa.String(), nullable=True),
    sa.Column('local_assembly', sa.String(), nullable=True),
    sa.Column('local_assembly_address', sa.String(), nullable=True),
    sa.Column('hall_name', sa.String(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('bed_number', sa.Integer(), nullable=True),
    sa.Column('extra_beds', sa.JSON(), nullable=True),
    sa.Column('active_status', sa.Enum('active', 'inactive', name='active_status_enum'), nullable=False),
    sa.ForeignKeyConstraint(['hall_name'], ['halls.hall_name'], ),
    sa.ForeignKeyConstraint(['phone_number_id'], ['phone_numbers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_images_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_phone_numbers_id'), table_name='phone_numbers')
    op.drop_table('phone_numbers')
    op.drop_index(op.f('ix_image_categories_id'), table_name='image_categories')
    op.drop_table('image_categories')
    op.drop_index(op.f('ix_halls_id'), table_name='halls')
    op.drop_table('halls')
    # ### end Alembic commands ###
