"""Field Propery fixes

Revision ID: 344cc491a603
Revises: ce7032f7045a
Create Date: 2025-12-08 15:02:23.940420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '344cc491a603'
down_revision: Union[str, None] = 'ce7032f7045a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('halls', 'no_beds',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('halls', 'no_beds',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
