"""ticketing table updatess ver 2.2

Revision ID: 3c9b2872f05e
Revises: a918be83ba3c
Create Date: 2026-03-02 11:19:45.974739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c9b2872f05e'
down_revision: Union[str, None] = 'a918be83ba3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
