"""add hall allocation fields to ministers

Revision ID: 45047fad8a96
Revises: 3c9b2872f05e
Create Date: 2026-03-15 01:19:45.265491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45047fad8a96'
down_revision: Union[str, None] = '3c9b2872f05e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ministers', sa.Column('hall_name', sa.String(), nullable=True))
    op.add_column('ministers', sa.Column('floor', sa.UUID(), nullable=True))
    op.add_column('ministers', sa.Column('bed_number', sa.String(), nullable=True))
    op.create_foreign_key(None, 'ministers', 'halls', ['hall_name'], ['hall_name'])
    op.create_foreign_key(None, 'ministers', 'hall_floors', ['floor'], ['floor_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ministers', type_='foreignkey')
    op.drop_constraint(None, 'ministers', type_='foreignkey')
    op.drop_column('ministers', 'bed_number')
    op.drop_column('ministers', 'floor')
    op.drop_column('ministers', 'hall_name')
    # ### end Alembic commands ###
