"""Primary Key Fixes

Revision ID: 52db91ed7035
Revises: 344cc491a603
Create Date: 2025-12-08 16:25:35.376270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52db91ed7035'
down_revision: Union[str, None] = '344cc491a603'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('floor_category_association', 'floor_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('floor_category_association', 'floor_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
