"""Hall Allocation Fix -3

Revision ID: 5b60d93f7a03
Revises: a40e7fcaa4ee
Create Date: 2025-08-16 14:51:40.046247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b60d93f7a03'
down_revision: Union[str, None] = 'a40e7fcaa4ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('halls', sa.Column('no_allocated_beds', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('halls', 'no_allocated_beds')
    # ### end Alembic commands ###
