"""ticketing table fixes

Revision ID: 8349a8f89e5d
Revises: 89e317e24561
Create Date: 2026-02-24 17:10:28.987696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8349a8f89e5d'
down_revision: Union[str, None] = '89e317e24561'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ministers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('room_number', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ministers_id'), 'ministers', ['id'], unique=False)
    op.create_index(op.f('ix_ministers_phone_number'), 'ministers', ['phone_number'], unique=True)
    op.create_table('meal_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('minister_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['minister_id'], ['ministers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('minister_id', 'date', name='uq_minister_date')
    )
    op.create_index(op.f('ix_meal_records_date'), 'meal_records', ['date'], unique=False)
    op.create_index(op.f('ix_meal_records_id'), 'meal_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meal_records_id'), table_name='meal_records')
    op.drop_index(op.f('ix_meal_records_date'), table_name='meal_records')
    op.drop_table('meal_records')
    op.drop_index(op.f('ix_ministers_phone_number'), table_name='ministers')
    op.drop_index(op.f('ix_ministers_id'), table_name='ministers')
    op.drop_table('ministers')
    # ### end Alembic commands ###
