"""add object key for images

Revision ID: 89e317e24561
Revises: d17f906cb017
Create Date: 2025-12-31 14:31:57.837902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89e317e24561'
down_revision: Union[str, None] = 'd17f906cb017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('object_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'object_key')
    # ### end Alembic commands ###
