"""Hall Allocation Fix -2

Revision ID: a40e7fcaa4ee
Revises: 04f4d07f5d98
Create Date: 2025-08-16 14:18:35.056449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a40e7fcaa4ee'
down_revision: Union[str, None] = '04f4d07f5d98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('halls', 'category_allocated')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('halls', sa.Column('category_allocated', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
