"""Hall Allocation Logic Fixes

Revision ID: a4e804e88bea
Revises: fac5523b9c66
Create Date: 2025-12-25 10:37:31.061279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4e804e88bea'
down_revision: Union[str, None] = 'fac5523b9c66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
