"""ticketing table updatess ver 2.1

Revision ID: a918be83ba3c
Revises: 10acccfd7ee6
Create Date: 2026-03-02 10:48:59.948811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a918be83ba3c'
down_revision: Union[str, None] = '10acccfd7ee6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
