"""Minor Fixes and updates

Revision ID: ac2fbcc75af2
Revises: 0f986d513ec9
Create Date: 2025-12-09 13:56:56.149313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac2fbcc75af2'
down_revision: Union[str, None] = '0f986d513ec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hall_floors', sa.Column('counter_value', sa.Integer(), nullable=True))
    op.alter_column('users', 'bed_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'bed_number',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('hall_floors', 'counter_value')
    # ### end Alembic commands ###
