"""Hall Allocation Fix for Extra Beds

Revision ID: bb9882f4c0a4
Revises: 5b60d93f7a03
Create Date: 2025-08-18 11:37:08.628511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb9882f4c0a4'
down_revision: Union[str, None] = '5b60d93f7a03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('extra_beds', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'extra_beds')
    # ### end Alembic commands ###
