"""initial migration

Revision ID: d6c55cc473d2
Revises: 
Create Date: 2025-08-04 13:18:37.422780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6c55cc473d2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('halls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hall_name', sa.String(), nullable=False),
    sa.Column('no_beds', sa.Integer(), nullable=False),
    sa.Column('category_allocated', sa.String(), nullable=False),
    sa.Column('no_floors', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hall_name')
    )
    op.create_index(op.f('ix_halls_id'), 'halls', ['id'], unique=False)
    op.create_table('phone_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('time_registered', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_phone_numbers_id'), 'phone_numbers', ['id'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.Column('hall_name', sa.String(), nullable=False),
    sa.Column('floor_allocated', sa.Integer(), nullable=False),
    sa.Column('no_beds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hall_name'], ['halls.hall_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('marital_status', sa.String(), nullable=False),
    sa.Column('no_children', sa.Integer(), nullable=True),
    sa.Column('names_children', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('arrival_date', sa.Date(), nullable=False),
    sa.Column('medical_issues', sa.String(), nullable=True),
    sa.Column('local_assembly', sa.String(), nullable=True),
    sa.Column('local_assembly_address', sa.String(), nullable=True),
    sa.Column('hall_name', sa.String(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('bed_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hall_name'], ['halls.hall_name'], ),
    sa.ForeignKeyConstraint(['phone_number_id'], ['phone_numbers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_phone_numbers_id'), table_name='phone_numbers')
    op.drop_table('phone_numbers')
    op.drop_index(op.f('ix_halls_id'), table_name='halls')
    op.drop_table('halls')
    # ### end Alembic commands ###
