"""Add Verification Date

Revision ID: f0d54082cec9
Revises: 30850b4c89a1
Create Date: 2025-12-21 14:33:01.294086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0d54082cec9'
down_revision: Union[str, None] = '30850b4c89a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_verified', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date_verified')
    # ### end Alembic commands ###
