"""Fields to support S3 file uploads

Revision ID: fac5523b9c66
Revises: f0d54082cec9
Create Date: 2025-12-24 20:21:22.886209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fac5523b9c66'
down_revision: Union[str, None] = 'f0d54082cec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('object_key', sa.String(), nullable=False))
    op.add_column('users', sa.Column('date_presigned_url_generated', sa.Date(), nullable=False))
    op.create_unique_constraint(None, 'users', ['object_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'date_presigned_url_generated')
    op.drop_column('users', 'object_key')
    # ### end Alembic commands ###
